// <auto-generated />
using System;
using MemoryGame_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryGameApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704215659_SeedDemoUsersAndGameResults")]
    partial class SeedDemoUsersAndGameResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPairs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfPairs = 4
                        },
                        new
                        {
                            Id = 2,
                            NumberOfPairs = 6
                        },
                        new
                        {
                            Id = 3,
                            NumberOfPairs = 8
                        },
                        new
                        {
                            Id = 4,
                            NumberOfPairs = 10
                        },
                        new
                        {
                            Id = 5,
                            NumberOfPairs = 12
                        },
                        new
                        {
                            Id = 6,
                            NumberOfPairs = 15
                        },
                        new
                        {
                            Id = 7,
                            NumberOfPairs = 18
                        },
                        new
                        {
                            Id = 8,
                            NumberOfPairs = 21
                        },
                        new
                        {
                            Id = 9,
                            NumberOfPairs = 25
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.ToTable("DifficultyTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            Label = "Easy",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            Label = "Facile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 2,
                            Label = "Medium",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 2,
                            Label = "Medio",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 5,
                            DifficultyId = 3,
                            Label = "Hard",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 6,
                            DifficultyId = 3,
                            Label = "Difficile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 7,
                            DifficultyId = 4,
                            Label = "Extreme",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 8,
                            DifficultyId = 4,
                            Label = "Estremo",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 9,
                            DifficultyId = 5,
                            Label = "Impossible",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 10,
                            DifficultyId = 5,
                            Label = "Impossibile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 11,
                            DifficultyId = 6,
                            Label = "Legendary",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 12,
                            DifficultyId = 6,
                            Label = "Leggendario",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 13,
                            DifficultyId = 7,
                            Label = "Mythical",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 14,
                            DifficultyId = 7,
                            Label = "Mitico",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 15,
                            DifficultyId = 8,
                            Label = "Divine",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 16,
                            DifficultyId = 8,
                            Label = "Divino",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 17,
                            DifficultyId = 9,
                            Label = "Godlike",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 18,
                            DifficultyId = 9,
                            Label = "Sovrumano",
                            LanguageCode = "it"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moves")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            Moves = 6,
                            PlayedAt = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            Moves = 8,
                            PlayedAt = new DateTime(2025, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 2,
                            Moves = 14,
                            PlayedAt = new DateTime(2025, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 3,
                            Moves = 20,
                            PlayedAt = new DateTime(2025, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            DifficultyId = 1,
                            Moves = 5,
                            PlayedAt = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            DifficultyId = 2,
                            Moves = 12,
                            PlayedAt = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            DifficultyId = 2,
                            Moves = 10,
                            PlayedAt = new DateTime(2025, 6, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            DifficultyId = 4,
                            Moves = 35,
                            PlayedAt = new DateTime(2025, 6, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo1@example.com",
                            PasswordHash = "$2a$11$5XPr6Kjk/jJmse1wP71jpO06ZLsknX/zDDRhp4Q8S..hOhUSXgwLC",
                            Role = 0,
                            Username = "demo_player1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo2@example.com",
                            PasswordHash = "$2a$11$5XPr6Kjk/jJmse1wP71jpO06ZLsknX/zDDRhp4Q8S..hOhUSXgwLC",
                            Role = 0,
                            Username = "demo_player2"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("Translations")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("GameResults")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoryGame_API.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Navigation("GameResults");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
