// <auto-generated />
using System;
using MemoryGame_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryGameApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708091138_AddGameResultDuration")]
    partial class AddGameResultDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MemoryGame_API.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FIRST_WIN",
                            Icon = "flag"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TEN_GAMES",
                            Icon = "local_fire_department"
                        },
                        new
                        {
                            Id = 3,
                            Code = "FIFTY_GAMES",
                            Icon = "military_tech"
                        },
                        new
                        {
                            Id = 4,
                            Code = "HUNDRED_GAMES",
                            Icon = "workspace_premium"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FLAWLESS",
                            Icon = "bolt"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ALL_DIFFICULTIES",
                            Icon = "travel_explore"
                        },
                        new
                        {
                            Id = 7,
                            Code = "HARDEST_DIFFICULTY",
                            Icon = "emoji_events"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NIGHT_OWL",
                            Icon = "nightlight"
                        },
                        new
                        {
                            Id = 9,
                            Code = "FIVE_HUNDRED_GAMES",
                            Icon = "diamond"
                        },
                        new
                        {
                            Id = 10,
                            Code = "EARLY_BIRD",
                            Icon = "wb_twilight"
                        },
                        new
                        {
                            Id = 11,
                            Code = "WEEKEND_WARRIOR",
                            Icon = "weekend"
                        },
                        new
                        {
                            Id = 12,
                            Code = "PERFECT_STREAK",
                            Icon = "auto_awesome"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MARATHON_DAY",
                            Icon = "directions_run"
                        },
                        new
                        {
                            Id = 14,
                            Code = "FLAWLESS_LEGEND",
                            Icon = "verified"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.AchievementTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("AchievementTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AchievementId = 1,
                            Description = "Complete your first game.",
                            LanguageCode = "en",
                            Name = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            AchievementId = 1,
                            Description = "Completa la tua prima partita.",
                            LanguageCode = "it",
                            Name = "Primi Passi"
                        },
                        new
                        {
                            Id = 3,
                            AchievementId = 2,
                            Description = "Play 10 games.",
                            LanguageCode = "en",
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 4,
                            AchievementId = 2,
                            Description = "Gioca 10 partite.",
                            LanguageCode = "it",
                            Name = "Habitué"
                        },
                        new
                        {
                            Id = 5,
                            AchievementId = 3,
                            Description = "Play 50 games.",
                            LanguageCode = "en",
                            Name = "Veteran"
                        },
                        new
                        {
                            Id = 6,
                            AchievementId = 3,
                            Description = "Gioca 50 partite.",
                            LanguageCode = "it",
                            Name = "Veterano"
                        },
                        new
                        {
                            Id = 7,
                            AchievementId = 4,
                            Description = "Play 100 games.",
                            LanguageCode = "en",
                            Name = "Legend"
                        },
                        new
                        {
                            Id = 8,
                            AchievementId = 4,
                            Description = "Gioca 100 partite.",
                            LanguageCode = "it",
                            Name = "Leggenda"
                        },
                        new
                        {
                            Id = 9,
                            AchievementId = 5,
                            Description = "Complete a game without a single wrong guess.",
                            LanguageCode = "en",
                            Name = "Iron Memory"
                        },
                        new
                        {
                            Id = 10,
                            AchievementId = 5,
                            Description = "Completa una partita senza sbagliare nemmeno una mossa.",
                            LanguageCode = "it",
                            Name = "Memoria di Ferro"
                        },
                        new
                        {
                            Id = 11,
                            AchievementId = 6,
                            Description = "Win at least one game on every difficulty.",
                            LanguageCode = "en",
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 12,
                            AchievementId = 6,
                            Description = "Vinci almeno una partita per ogni difficoltà.",
                            LanguageCode = "it",
                            Name = "Esploratore"
                        },
                        new
                        {
                            Id = 13,
                            AchievementId = 7,
                            Description = "Win a game on the hardest difficulty.",
                            LanguageCode = "en",
                            Name = "Godlike"
                        },
                        new
                        {
                            Id = 14,
                            AchievementId = 7,
                            Description = "Vinci una partita nella difficoltà più alta.",
                            LanguageCode = "it",
                            Name = "Sovrumano"
                        },
                        new
                        {
                            Id = 15,
                            AchievementId = 8,
                            Description = "Complete a game between midnight and 5 AM.",
                            LanguageCode = "en",
                            Name = "Night Owl"
                        },
                        new
                        {
                            Id = 16,
                            AchievementId = 8,
                            Description = "Completa una partita tra mezzanotte e le 5 del mattino.",
                            LanguageCode = "it",
                            Name = "Nottambulo"
                        },
                        new
                        {
                            Id = 17,
                            AchievementId = 1,
                            Description = "Termine ta première partie.",
                            LanguageCode = "fr",
                            Name = "Premiers Pas"
                        },
                        new
                        {
                            Id = 18,
                            AchievementId = 1,
                            Description = "Schließe dein erstes Spiel ab.",
                            LanguageCode = "de",
                            Name = "Erste Schritte"
                        },
                        new
                        {
                            Id = 19,
                            AchievementId = 2,
                            Description = "Joue 10 parties.",
                            LanguageCode = "fr",
                            Name = "Habitué"
                        },
                        new
                        {
                            Id = 20,
                            AchievementId = 2,
                            Description = "Spiele 10 Partien.",
                            LanguageCode = "de",
                            Name = "Stammspieler"
                        },
                        new
                        {
                            Id = 21,
                            AchievementId = 3,
                            Description = "Joue 50 parties.",
                            LanguageCode = "fr",
                            Name = "Vétéran"
                        },
                        new
                        {
                            Id = 22,
                            AchievementId = 3,
                            Description = "Spiele 50 Partien.",
                            LanguageCode = "de",
                            Name = "Veteran"
                        },
                        new
                        {
                            Id = 23,
                            AchievementId = 4,
                            Description = "Joue 100 parties.",
                            LanguageCode = "fr",
                            Name = "Légende"
                        },
                        new
                        {
                            Id = 24,
                            AchievementId = 4,
                            Description = "Spiele 100 Partien.",
                            LanguageCode = "de",
                            Name = "Legende"
                        },
                        new
                        {
                            Id = 25,
                            AchievementId = 5,
                            Description = "Termine une partie sans la moindre erreur.",
                            LanguageCode = "fr",
                            Name = "Mémoire de Fer"
                        },
                        new
                        {
                            Id = 26,
                            AchievementId = 5,
                            Description = "Schließe eine Partie ohne einen einzigen Fehlversuch ab.",
                            LanguageCode = "de",
                            Name = "Eisernes Gedächtnis"
                        },
                        new
                        {
                            Id = 27,
                            AchievementId = 6,
                            Description = "Gagne au moins une partie à chaque niveau de difficulté.",
                            LanguageCode = "fr",
                            Name = "Explorateur"
                        },
                        new
                        {
                            Id = 28,
                            AchievementId = 6,
                            Description = "Gewinne mindestens eine Partie auf jedem Schwierigkeitsgrad.",
                            LanguageCode = "de",
                            Name = "Entdecker"
                        },
                        new
                        {
                            Id = 29,
                            AchievementId = 7,
                            Description = "Gagne une partie au niveau de difficulté le plus élevé.",
                            LanguageCode = "fr",
                            Name = "Surhumain"
                        },
                        new
                        {
                            Id = 30,
                            AchievementId = 7,
                            Description = "Gewinne eine Partie auf dem höchsten Schwierigkeitsgrad.",
                            LanguageCode = "de",
                            Name = "Übermenschlich"
                        },
                        new
                        {
                            Id = 31,
                            AchievementId = 8,
                            Description = "Termine une partie entre minuit et 5 heures du matin.",
                            LanguageCode = "fr",
                            Name = "Oiseau de Nuit"
                        },
                        new
                        {
                            Id = 32,
                            AchievementId = 8,
                            Description = "Schließe eine Partie zwischen Mitternacht und 5 Uhr morgens ab.",
                            LanguageCode = "de",
                            Name = "Nachteule"
                        },
                        new
                        {
                            Id = 33,
                            AchievementId = 9,
                            Description = "Play 500 games.",
                            LanguageCode = "en",
                            Name = "Unstoppable"
                        },
                        new
                        {
                            Id = 34,
                            AchievementId = 9,
                            Description = "Gioca 500 partite.",
                            LanguageCode = "it",
                            Name = "Inarrestabile"
                        },
                        new
                        {
                            Id = 35,
                            AchievementId = 9,
                            Description = "Joue 500 parties.",
                            LanguageCode = "fr",
                            Name = "Inarrêtable"
                        },
                        new
                        {
                            Id = 36,
                            AchievementId = 9,
                            Description = "Spiele 500 Partien.",
                            LanguageCode = "de",
                            Name = "Unaufhaltsam"
                        },
                        new
                        {
                            Id = 37,
                            AchievementId = 10,
                            Description = "Complete a game between 5 AM and 8 AM.",
                            LanguageCode = "en",
                            Name = "Early Bird"
                        },
                        new
                        {
                            Id = 38,
                            AchievementId = 10,
                            Description = "Completa una partita tra le 5 e le 8 del mattino.",
                            LanguageCode = "it",
                            Name = "Mattiniero"
                        },
                        new
                        {
                            Id = 39,
                            AchievementId = 10,
                            Description = "Termine une partie entre 5 h et 8 h du matin.",
                            LanguageCode = "fr",
                            Name = "Lève-tôt"
                        },
                        new
                        {
                            Id = 40,
                            AchievementId = 10,
                            Description = "Schließe eine Partie zwischen 5 und 8 Uhr morgens ab.",
                            LanguageCode = "de",
                            Name = "Frühaufsteher"
                        },
                        new
                        {
                            Id = 41,
                            AchievementId = 11,
                            Description = "Play a game on Saturday or Sunday.",
                            LanguageCode = "en",
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 42,
                            AchievementId = 11,
                            Description = "Gioca una partita di sabato o domenica.",
                            LanguageCode = "it",
                            Name = "Guerriero del Weekend"
                        },
                        new
                        {
                            Id = 43,
                            AchievementId = 11,
                            Description = "Joue une partie le samedi ou le dimanche.",
                            LanguageCode = "fr",
                            Name = "Guerrier du Week-end"
                        },
                        new
                        {
                            Id = 44,
                            AchievementId = 11,
                            Description = "Spiele eine Partie am Samstag oder Sonntag.",
                            LanguageCode = "de",
                            Name = "Wochenendkrieger"
                        },
                        new
                        {
                            Id = 45,
                            AchievementId = 12,
                            Description = "Complete 3 flawless games.",
                            LanguageCode = "en",
                            Name = "Perfectionist"
                        },
                        new
                        {
                            Id = 46,
                            AchievementId = 12,
                            Description = "Completa 3 partite senza errori.",
                            LanguageCode = "it",
                            Name = "Perfezionista"
                        },
                        new
                        {
                            Id = 47,
                            AchievementId = 12,
                            Description = "Termine 3 parties sans la moindre erreur.",
                            LanguageCode = "fr",
                            Name = "Perfectionniste"
                        },
                        new
                        {
                            Id = 48,
                            AchievementId = 12,
                            Description = "Schließe 3 fehlerfreie Partien ab.",
                            LanguageCode = "de",
                            Name = "Perfektionist"
                        },
                        new
                        {
                            Id = 49,
                            AchievementId = 13,
                            Description = "Play 5 games in a single day.",
                            LanguageCode = "en",
                            Name = "Marathon Runner"
                        },
                        new
                        {
                            Id = 50,
                            AchievementId = 13,
                            Description = "Gioca 5 partite in un solo giorno.",
                            LanguageCode = "it",
                            Name = "Maratoneta"
                        },
                        new
                        {
                            Id = 51,
                            AchievementId = 13,
                            Description = "Joue 5 parties en une seule journée.",
                            LanguageCode = "fr",
                            Name = "Marathonien"
                        },
                        new
                        {
                            Id = 52,
                            AchievementId = 13,
                            Description = "Spiele 5 Partien an einem einzigen Tag.",
                            LanguageCode = "de",
                            Name = "Marathonläufer"
                        },
                        new
                        {
                            Id = 53,
                            AchievementId = 14,
                            Description = "Complete the hardest difficulty flawlessly.",
                            LanguageCode = "en",
                            Name = "Flawless Legend"
                        },
                        new
                        {
                            Id = 54,
                            AchievementId = 14,
                            Description = "Completa la difficoltà più alta senza errori.",
                            LanguageCode = "it",
                            Name = "Leggenda Perfetta"
                        },
                        new
                        {
                            Id = 55,
                            AchievementId = 14,
                            Description = "Termine le niveau de difficulté le plus élevé sans la moindre erreur.",
                            LanguageCode = "fr",
                            Name = "Légende Parfaite"
                        },
                        new
                        {
                            Id = 56,
                            AchievementId = 14,
                            Description = "Schließe den höchsten Schwierigkeitsgrad fehlerfrei ab.",
                            LanguageCode = "de",
                            Name = "Makellose Legende"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPairs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfPairs = 4
                        },
                        new
                        {
                            Id = 2,
                            NumberOfPairs = 6
                        },
                        new
                        {
                            Id = 3,
                            NumberOfPairs = 8
                        },
                        new
                        {
                            Id = 4,
                            NumberOfPairs = 10
                        },
                        new
                        {
                            Id = 5,
                            NumberOfPairs = 12
                        },
                        new
                        {
                            Id = 6,
                            NumberOfPairs = 15
                        },
                        new
                        {
                            Id = 7,
                            NumberOfPairs = 18
                        },
                        new
                        {
                            Id = 8,
                            NumberOfPairs = 21
                        },
                        new
                        {
                            Id = 9,
                            NumberOfPairs = 25
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.ToTable("DifficultyTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            Label = "Easy",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            Label = "Facile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 2,
                            Label = "Medium",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 2,
                            Label = "Medio",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 5,
                            DifficultyId = 3,
                            Label = "Hard",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 6,
                            DifficultyId = 3,
                            Label = "Difficile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 7,
                            DifficultyId = 4,
                            Label = "Extreme",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 8,
                            DifficultyId = 4,
                            Label = "Estremo",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 9,
                            DifficultyId = 5,
                            Label = "Impossible",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 10,
                            DifficultyId = 5,
                            Label = "Impossibile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 11,
                            DifficultyId = 6,
                            Label = "Legendary",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 12,
                            DifficultyId = 6,
                            Label = "Leggendario",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 13,
                            DifficultyId = 7,
                            Label = "Mythical",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 14,
                            DifficultyId = 7,
                            Label = "Mitico",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 15,
                            DifficultyId = 8,
                            Label = "Divine",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 16,
                            DifficultyId = 8,
                            Label = "Divino",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 17,
                            DifficultyId = 9,
                            Label = "Godlike",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 18,
                            DifficultyId = 9,
                            Label = "Sovrumano",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 19,
                            DifficultyId = 1,
                            Label = "Facile",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 20,
                            DifficultyId = 1,
                            Label = "Einfach",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 21,
                            DifficultyId = 2,
                            Label = "Moyen",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 22,
                            DifficultyId = 2,
                            Label = "Mittel",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 23,
                            DifficultyId = 3,
                            Label = "Difficile",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 24,
                            DifficultyId = 3,
                            Label = "Schwer",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 25,
                            DifficultyId = 4,
                            Label = "Extrême",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 26,
                            DifficultyId = 4,
                            Label = "Extrem",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 27,
                            DifficultyId = 5,
                            Label = "Impossible",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 28,
                            DifficultyId = 5,
                            Label = "Unmöglich",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 29,
                            DifficultyId = 6,
                            Label = "Légendaire",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 30,
                            DifficultyId = 6,
                            Label = "Legendär",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 31,
                            DifficultyId = 7,
                            Label = "Mythique",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 32,
                            DifficultyId = 7,
                            Label = "Mythisch",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 33,
                            DifficultyId = 8,
                            Label = "Divin",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 34,
                            DifficultyId = 8,
                            Label = "Göttlich",
                            LanguageCode = "de"
                        },
                        new
                        {
                            Id = 35,
                            DifficultyId = 9,
                            Label = "Surhumain",
                            LanguageCode = "fr"
                        },
                        new
                        {
                            Id = 36,
                            DifficultyId = 9,
                            Label = "Übermenschlich",
                            LanguageCode = "de"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moves")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            DurationSeconds = 0,
                            Moves = 6,
                            PlayedAt = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            DurationSeconds = 0,
                            Moves = 8,
                            PlayedAt = new DateTime(2025, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 2,
                            DurationSeconds = 0,
                            Moves = 14,
                            PlayedAt = new DateTime(2025, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 3,
                            DurationSeconds = 0,
                            Moves = 20,
                            PlayedAt = new DateTime(2025, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            DifficultyId = 1,
                            DurationSeconds = 0,
                            Moves = 5,
                            PlayedAt = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            DifficultyId = 2,
                            DurationSeconds = 0,
                            Moves = 12,
                            PlayedAt = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            DifficultyId = 2,
                            DurationSeconds = 0,
                            Moves = 10,
                            PlayedAt = new DateTime(2025, 6, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            DifficultyId = 4,
                            DurationSeconds = 0,
                            Moves = 35,
                            PlayedAt = new DateTime(2025, 6, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo1@example.com",
                            PasswordHash = "$2a$11$5XPr6Kjk/jJmse1wP71jpO06ZLsknX/zDDRhp4Q8S..hOhUSXgwLC",
                            Role = 0,
                            Username = "demo_player1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo2@example.com",
                            PasswordHash = "$2a$11$5XPr6Kjk/jJmse1wP71jpO06ZLsknX/zDDRhp4Q8S..hOhUSXgwLC",
                            Role = 0,
                            Username = "demo_player2"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("MemoryGame_API.Models.AchievementTranslation", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Achievement", "Achievement")
                        .WithMany("Translations")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("Translations")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("GameResults")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoryGame_API.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryGame_API.Models.UserAchievement", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoryGame_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryGame_API.Models.Achievement", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Navigation("GameResults");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
