// <auto-generated />
using System;
using MemoryGame_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryGame_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPairs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfPairs = 4
                        },
                        new
                        {
                            Id = 2,
                            NumberOfPairs = 6
                        },
                        new
                        {
                            Id = 3,
                            NumberOfPairs = 8
                        },
                        new
                        {
                            Id = 4,
                            NumberOfPairs = 10
                        },
                        new
                        {
                            Id = 5,
                            NumberOfPairs = 12
                        },
                        new
                        {
                            Id = 6,
                            NumberOfPairs = 15
                        },
                        new
                        {
                            Id = 7,
                            NumberOfPairs = 18
                        },
                        new
                        {
                            Id = 8,
                            NumberOfPairs = 21
                        },
                        new
                        {
                            Id = 9,
                            NumberOfPairs = 25
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.ToTable("DifficultyTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            Label = "Easy",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            Label = "Facile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 2,
                            Label = "Medium",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 2,
                            Label = "Medio",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 5,
                            DifficultyId = 3,
                            Label = "Hard",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 6,
                            DifficultyId = 3,
                            Label = "Difficile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 7,
                            DifficultyId = 4,
                            Label = "Extreme",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 8,
                            DifficultyId = 4,
                            Label = "Estremo",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 9,
                            DifficultyId = 5,
                            Label = "Impossible",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 10,
                            DifficultyId = 5,
                            Label = "Impossibile",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 11,
                            DifficultyId = 6,
                            Label = "Legendary",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 12,
                            DifficultyId = 6,
                            Label = "Leggendario",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 13,
                            DifficultyId = 7,
                            Label = "Mythical",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 14,
                            DifficultyId = 7,
                            Label = "Mitico",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 15,
                            DifficultyId = 8,
                            Label = "Divine",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 16,
                            DifficultyId = 8,
                            Label = "Divino",
                            LanguageCode = "it"
                        },
                        new
                        {
                            Id = 17,
                            DifficultyId = 9,
                            Label = "Godlike",
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = 18,
                            DifficultyId = 9,
                            Label = "Sovrumano",
                            LanguageCode = "it"
                        });
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moves")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MemoryGame_API.Models.DifficultyTranslation", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("Translations")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("MemoryGame_API.Models.GameResult", b =>
                {
                    b.HasOne("MemoryGame_API.Models.Difficulty", "Difficulty")
                        .WithMany("GameResults")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoryGame_API.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryGame_API.Models.Difficulty", b =>
                {
                    b.Navigation("GameResults");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MemoryGame_API.Models.User", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
